---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shop-db
  namespace: shop-dev
spec:
  encryptedData:
    password: AgCLVbL4owiOeoH+bGiHQ4dAGiFdIfdrIZ30MDjLaFtkkowthYekazIB4ClgICgP8LN6XAMe1us/C5Y6CEWkZncIgOsOYuZ6omHIiCh//xYH1mgnoVIFD1sIbJRje2b8D4W1UOTkgT5nIUaW+rJ6uAGjj4fwodnXpwiv5DYZrC8vqMfbjxx1DJzIiYeRCd3z/Gp8os+QnVLudlvPNaVvz1YW7hTw8DoTwmhHJ0W2Qvto71Qb/zsN71vIEQOVcIxS+tWMx2NMW2J2CwFtk/r7yuEczLy+8dh3YqvaoE7t3qbhkKYVkkhhPnRYVEMiqujvOC2Px+vR7vO35cHIqSAs3ITO5ksAr3ZRV+9grATq345gcUvGCS0GlODsicQHi5gZ2VaLTY+KR79pysiRyypvVRN2aN6BRCrh14qMPxCQxDWj0hMJ2QbRHpaBgvOhJbFsG+W6BqCDhc3I4U++SL9ZZzCf1Ji6VIQpjpPBPff1miDkUE/BJYSI1IngpK+gps5ut8dj8Q9x/g5v2NvxHMNnJ4CkPnaLAOMyyMnLQMGQMiHKhMWiGk0Wtr7AviDvgO363fgeq6SRqgrmqc7aeaAtMx+MELZNEBbfXnJdh6lBLCEuC+Z12caFNKW5W5UtjpmHtXV2/OdgJHZ6XwrNGlJpkKtF/+gbC6ZwTxEqCGhtlayvkRTGG8NskPIpGh1KkUqv/TnAEnHwE3KadhEo8jZXM64=
  template:
    metadata:
      name: shop-db
      namespace: default
