# kind-Cluster fuer die Argo CD Schulung
# Port-Mappings: 8080 -> Argo CD UI (NodePort 30080), 8081 -> Kaffee-Shop dev (30081), 8082 -> prod (30082)
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: schulung
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
      - containerPort: 30082
        hostPort: 8082
        protocol: TCP
      - containerPort: 30083
        hostPort: 8083
        protocol: TCP
      - containerPort: 30084      # Kubernetes Dashboard (Kong-Proxy)
        hostPort: 8084
        protocol: TCP
